# Generated by Django 3.0.6 on 2020-06-08 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0001_initial'),
        ('situacao', '0001_initial'),
        ('pagar', '0002_pagar_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagar',
            name='situacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='situacao.Situacao'),
        ),
        migrations.AddField(
            model_name='pagar',
            name='transacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transacao.Transacao'),
        ),
    ]
