# Generated by Django 3.0.6 on 2020-06-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagar', '0003_auto_20200608_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagar',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagar',
            name='data_vencimento',
            field=models.DateField(null=True),
        ),
    ]
