# Generated by Django 3.0.6 on 2020-06-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagar', '0005_pagar_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagar',
            name='descricao',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
