# Generated by Django 3.0.6 on 2020-06-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classificacao', '0001_initial'),
        ('transacao', '0001_initial'),
        ('situacao', '0001_initial'),
        ('receber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receber',
            name='classificacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classificacao.Classificacao'),
        ),
        migrations.AddField(
            model_name='receber',
            name='data_recebimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='receber',
            name='situacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='situacao.Situacao'),
        ),
        migrations.AddField(
            model_name='receber',
            name='transacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transacao.Transacao'),
        ),
        migrations.AddField(
            model_name='receber',
            name='valor',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
