# Generated by Django 3.0.6 on 2020-06-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receber', '0002_auto_20200609_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='receber',
            name='tag',
            field=models.CharField(default='R', max_length=1),
        ),
    ]
